### ISSUE TITLE
Handbook Analytics

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/handbook#1087]
I have a [wishlist](https://docs.google.com/document/d/1Dg6xuMzlMQkWmM7RmfBrfnLhE70GLzhw8LwNqdFUPx8/edit) of analytics to track for the Handbook. Netlify + datadog will not get us what is needed here.

I would like to try the following options, which are similar in price and features:

https://usefathom.com/

https://plausible.io/

**Comment by jeanduplessis** [comment]
@marybelzer now that we have both these platforms to test I'm assigning this issue to you to review which one we want to keep.

**Comment by marybelzer** [comment]
Decided on Plausible, @jeanduplessis is planning on re-activating the account.
