### ISSUE TITLE
Many links on org chart page are broken

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/handbook#136]
A lot of the links on https://handbook.sourcegraph.com/company/team/org_chart are broken - possibly something to do with the auto-generated redirects and nested lists? For instance, the "Code graph" link goes to https://handbook.sourcegraph.com/company/team/code-graph but should be https://handbook.sourcegraph.com/engineering/code-graph.

**Comment by felixfbecker** [comment]
Redirects are a red herring here, as the link in the rendered HTML is actually wrong:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/10532611/136756376-069a1278-3bff-4d03-a112-e1f340b68a9d.png">

I'd guess there is a bug in the link rewrite/resolution logic: 
https://github.com/sourcegraph/handbook/blob/ec9217ca08bdfdb81de82b7cb289b6d85879b630/src/lib/markdownToHtml.ts#L78:10

**Comment by felixfbecker** [comment]
Actually, I think you are right, this is about redirects. The links are correct.
