### ISSUE TITLE
data: include Slack handles in `data/team.yml`

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/handbook#1445]
https://github.com/sourcegraph/handbook/blob/main/data/team.yml already contains emails and some other nice metadata. If we had Slack handles as well, it would greatly improve the ease of automation around pinging for notifications, e.g. https://github.com/sourcegraph/sourcegraph/issues/25454 and https://github.com/sourcegraph/sourcegraph/pull/28759

**Comment by jhchabran** [comment]
TIL this exists! Actually, as we can list Slack usernames without the custom fields easily and without being worried of rate limited on the slack api, we could have a linter/checker that tells us who is missing pretty easily.

**Comment by bobheadxi** [comment]
We can also have a simple script to populate (hopefully) most of the list using some of the work you did in `sg teammate` with usernames to start off

**Comment by jhchabran** [comment]
We actually don't need to do that, because we can just use the email defined in that file to get the right slack user thanks to an API call (https://api.slack.com/methods/users.lookupByEmail) as all emails in there are all `@sourcegraph.com` which maps 1:1 to the slack accounts.

**Comment by bobheadxi** [comment]
> we can just use the email defined in that file to get the right slack user thanks to an API call (api.slack.com/methods/users.lookupByEmail) as all emails in there are all @sourcegraph.com which maps 1:1 to the slack accounts.

Ooh that's brilliant!
