### ISSUE TITLE
Bad links from "Benefits, Pay, and Perks" index page

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/handbook#1822]
The links from the "Benefits, Pay, and Perks" [index page](https://handbook.sourcegraph.com/benefits-pay-perks/) are broken, seemingly because they add an extra `/benefits-pay-perks` to the slug. For example, the holidays link redirects to `https://handbook.sourcegraph.com/benefits-pay-perks/benefits-pay-perks/benefits-perks/holidays`. 

I looked at fixing this, but interestingly, I can't reproduce the issue locally.

**Comment by marybelzer** [comment]
Seems like similar behavior happening here: https://sourcegraph.slack.com/archives/C02DUPNT7GW/p1643063427010600

**Comment by katyhoward** [comment]
Also: https://sourcegraph.slack.com/archives/CQ44Y7F4G/p1643667191678949

**Comment by felixfbecker** [comment]
Might be a bug in the redirect logic. Redirects are generated for Netlify and for Next.JS (locally), so that would explain why it works locally. They can be checked in the `_redirects` file (and also in dev tools network tab when following the links if "Preserve history" is on)

**Comment by jasonyavorsky** [comment]
There's a warning whenever you run `yarn dev` now, maybe it's related:

```
Warning: total number of custom routes exceeds 1000, this can reduce performance. Route counts:
headers: 0
rewrites: 0
redirects: 1236
See more info: https://nextjs.org/docs/messages/max-custom-routes-reached
```

**Comment by felixfbecker** [comment]
Sounds like a harmless warning though
