### ISSUE TITLE
Product compatibility table overflows onto right-side menu

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/handbook#1934]
On [this page](https://handbook.sourcegraph.com/departments/product-engineering/product/tools/feature_compatibility), the tables all overflow into the right-side menu. Curious if this might be related to https://github.com/sourcegraph/handbook/issues/789.

![image (1)](https://user-images.githubusercontent.com/73856596/150878818-4d3182fd-6f8f-428c-98ed-5522fa391195.png)

**Comment by felixfbecker** [comment]
This was probably (re?)introduced by https://github.com/sourcegraph/handbook/pull/1764. I think sticky table headers and horizontally scrolling tables are fundamentally incompatible, we need to find a way to only apply horizontal scrolling to tables without sticky headers.
