### ISSUE TITLE
Date tooltips think fiscal years start in August

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/handbook#2520]
This could be misleading because the OKRs page is linked from the onboarding checklist, and a new hire doesn't know yet how fiscal years work:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/10532611/155625882-07a3f0a7-d926-42d8-a45b-3ff95d36cd6c.png">

Code: https://sourcegraph.com/github.com/sourcegraph/handbook/-/blob/src/lib/dateHighlighter.ts

**Comment by st0nebreaker** [comment]
Adding fiscal year quarter end years being wrong in the tooltip as well.
![image](https://user-images.githubusercontent.com/59381432/167943291-0719c696-7925-4e38-a7fb-1af833a4143a.png)
