### ISSUE TITLE
Improve org chart page

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/handbook#61]
We currently render the org chart by compiling all team pages' "Members" sections.

That is not a bad approach per se, but we do it all in the _client_ at load time, which is noticeable and breaks often. For example, we currently seem to be adding a footer in the middle of the page, and date/time hover tooltips don't work in the dynamic content. The content can also not be searched I assume.

If we want to continue with this, we should look into doing this at build time. But also we should think about what the "ideal" org chart would look like for our handbook – perhaps data taken from the BambooHR API. Perhaps even a real _chart_ (although those don't necessarily scale better, rather the opposite).

**Comment by nicksnyder** [comment]
I think we should solve this more generally and not over index on the org chart use case. Idea here: https://github.com/sourcegraph/handbook/issues/649

**Comment by jasonyavorsky** [comment]
You might be able to achieve this pretty simply by adding a `manager` field to team.yml. This is what https://gitlab.com/gitlab-com/www-gitlab-com/blob/9250f34a3902e7ba8b5f8e57ef5024b3ffd2056f/data/team.yml does (though with an added layer of indirection by having a role slug assigned to everyone.)

**Comment by marybelzer** [comment]
Discovered a bug on this page: [#818](https://github.com/sourcegraph/handbook/issues/818)

**Comment by jasonyavorsky** [comment]
I implemented my idea above for the product team at https://github.com/sourcegraph/handbook/pull/895. If we like it we could expand it to the whole company and replace this page.

**Comment by marybelzer** [comment]
Curious if we can close this due to the work done in #1763 , or if we need to explore further?

**Comment by felixfbecker** [comment]
I haven't been following that work, but the org chart page still says "The org chart is generated automatically from team pages in the handbook (need to edit it?).". Is that wrong?

**Comment by jasonyavorsky** [comment]
I just updated the edit instructions via https://github.com/sourcegraph/handbook/pull/1976, I think with that this can indeed be closed.

**Comment by marybelzer** [comment]
thanks @jyavorska !
