### ISSUE TITLE
Levels table is broken

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/handbook#789]
Currently, the levels table is broken on both Firefox and Chrome, causing some of the descriptions of IC1 to be cut off.

![Uploading Screen Shot 2021-11-09 at 08.09.36.png…]()

**Comment by marybelzer** [comment]
@camdencheek can you share a link to the page you were seeing this on? doesn't look like the screen shot attached properly.

**Comment by camdencheek** [comment]
Whoops! Yes, it's on [this](https://handbook.sourcegraph.com/departments/product-engineering/engineering/career-development/framework) page. 

New screenshot:
<img width="953" alt="Screen Shot 2022-01-04 at 09 09 54" src="https://user-images.githubusercontent.com/12631702/148088609-cc38829f-b4e5-4f93-9f2f-d7994cd6bb2f.png">

**Comment by felixfbecker** [comment]
This was closed by https://github.com/sourcegraph/handbook/pull/1764
