### ISSUE TITLE
Video is missing captions on "Using relative paths to link handbook pages" page

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/handbook#81]
The video at https://handbook.sourcegraph.com/editing/linking-within-handbook is missing captions.

Captions can be added to this video following the guide at https://handbook.sourcegraph.com/marketing/adding_screenshots_screen_recording#adding-captions-for-your-voice-over-to-your-video

**Comment by InesRoitman** [comment]
Okay, I created the subtitles and uploaded them to the handbook folder in Gcloud. However... you know I cannot do the markdown URLs. I simply cannot get them. Could either of you add them, please? This is the name of the file Relative-paths-in-the-handbook.vtt @felixfbecker @jeanduplessis

**Comment by felixfbecker** [comment]
Done, check it out at https://handbook.sourcegraph.com/editing/linking-within-handbook 😊 

Thanks for the captions @InesRoitman, they are perfect!
