### ISSUE TITLE
Org chart page pulling in more content than desired

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/handbook#818]
The [org chart](https://handbook.sourcegraph.com/company/team/org_chart) page seems to be pulling in more from other pages than intended.

In the [org chart file](https://github.com/sourcegraph/handbook/edit/main/content/company/team/org_chart.md) specific sections from other team pages are linked, indicating we might only want to show the team member info from those pages. Instead, it looks like all of most of the pages are being pulled in. This is making the page less effective, and it's breaking some links in the side bar.

For example, clicking the "Marketing" section in the right side bar brings you to the "Marketing" heading underneath the customer support section, rather than the Marketing section itself.

**Comment by nicksnyder** [comment]
Yes, this is a bug. It didn't use to do this, so not sure when this broke.

**Comment by jasonyavorsky** [comment]
Maybe better to fix this by adding `role` and `reports_to` fields in the `team.yml` and generate this the same way as other generated content?

**Comment by nicksnyder** [comment]
cc @InesRoitman

**Comment by jasonyavorsky** [comment]
https://github.com/sourcegraph/handbook/pull/895 implements a `reports_to` field.
